Additional class documentation
ACF-Team/ACF-3 pull request #399
Opened 2024-04-10 23:33 UTC by LengthenedGradient

Following up from the previous documentation update, this one should document the remainder of the base class files.

2024-04-12 04:19 UTC, TwistedTail requested changes
Seems fine, just a few missing things and a couple misleading comments in relation to Add*Functions methods.

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/grouped.lua
> +--- @param Namespace table The namespace to store the groups under
The namespace in this case will be the table that will receive the new functions.

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/grouped.lua
> +--- @param Namespace string The table to store the group in
On this one, the namespace will be used to look for a group

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/grouped.lua
> +--- @return table Group The created group
This value can be nil under certain cases

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/grouped.lua
> +--- @return table Class The created group item
This value can be nil under certain conditions

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/object.lua
> +--- @return table # The created object
This value can be nil under certain conditions

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/simple.lua
> +--- @return table Class The created simple class
This value can be nil under certain conditions

2024-04-12 04:19 UTC, TwistedTail commented on lua/acf/core/classes/simple.lua
> +--- @param Namespace table The namespace to store the simple classes under
Same as the grouped ones, the namespace given to this function will receive a new set of functions

2024-04-13 02:57 UTC, TwistedTail approved these changes
Looks fine now

2024-04-13 06:49 UTC, LengthenedGradient commented
As of the namespace documentation update, In various places I have things like (objects/simple classes/groups) written. It makes no sense to call them classes because an object is not a class. What else could I call it?

2024-04-13 08:27 UTC, TwistedTail commented
> In various places I have things like (objects/simple classes/groups) written. It makes no sense to call them classes because an object is not a class. What else could I call it?

Personally I would just refer to them as "entries", but I suppose someone else could come up with a better term.

2024-04-13 14:32 UTC, LengthenedGradient commented
> > In various places I have things like (objects/simple classes/groups) written. It makes no sense to call them classes because an object is not a class. What else could I call it?
> 
> Personally I would just refer to them as "entries", but I suppose someone else could come up with a better term.

I just went with entries, that should work.

2024-04-13 23:57 UTC, TwistedTail commented
Anything else you might want to add/change? It seems alright.

2024-04-14 00:32 UTC, LengthenedGradient commented
> Anything else you might want to add/change? It seems alright.

I think this is ready to be merged. I don't think I'll need to add/change anything else.

2024-04-14 01:20 UTC, thecraftianman approved these changes

2024-04-14 01:21 UTC, merged